version: '3.8'

services:
  api:
    container_name: gleanr-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      - ENVIRONMENT=development