"""article

Revision ID: a6239a8319f7
Revises: d3f934a1a788
Create Date: 2025-04-09 13:23:34.334576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6239a8319f7'
down_revision: Union[str, None] = 'd3f934a1a788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('authors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('article', sa.Column('top_image', sa.String(), nullable=True))
    op.add_column('article', sa.Column('site_name', sa.String(), nullable=True))
    op.add_column('article', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('article', 'published_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('article', 'image_url')
    op.drop_column('article', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('article', 'published_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('article', 'description')
    op.drop_column('article', 'site_name')
    op.drop_column('article', 'top_image')
    op.drop_column('article', 'authors')
    # ### end Alembic commands ###
